version: '2'
services:
  web:
    image: nginx:latest
    links:
      - php
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - php    
  php:
    build: php-8.0-fpm
    environment:
      - TYPO3_CONTEXT=Development/Docker
    links:
      - db
      - redis
    volumes:
      - ./htdocs:/var/www/html
  db:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - '3306:3306'  
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:latest
    links:
      - db:db
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: secret
    ports:
      - '8080:80'
  redis:
    image: redis:latest
